### PR TITLE
Catch up to Tailwind 3.0.18

### PR DESCRIPTION
**Pull request by jamesnvc**
As discussed in #79, Tailwind has added a number of features now.

<strike>This PR is still in-progress; just putting it up here for visibility and to facilitate discussion on which features are desirable, if there's a better way, etc.</strike>

Based on Tailwind's [CHANGELOG](https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md#202---2020-12-11), I see the following tasks to accomplish:

 - [X] cursor-help
 - [x] filter
 - [x] backdrop-filter
 - [X] list-item
 - [X] inline-table
 - [X] isolation
 - [X] box-decoration-berak
 - [X] mix-blend-mode
 - [X] background-blend-mode
 - [X] background-origin
 - [X] rename lightBlue to sky
 - [X] support other variants for group-
 - [X] add peer-* variants
 - [x] shortcut syntax for opacity (already supported in girouette, as `-N` instead of `/N`)
 - [x] content utilities
 - [x] per-side border colours
 - [x] self-baseline utility
 - [x] aspect-ratio
 - [x] accent-color
 - [x] scroll-behavior
 - [x] will-change
 - [x] text-indent
 - [x] column
 - [x] border-hidden
 - [x] align-sub, align-super
 - [x] break-before, break-inside, break-after
 - [x] file variant for file-selector-button
 - [x] touch-action
 - [x] overflow-clip, overflow-x-clip, overflow-y-clip
 - [x] [open] variant
 - [x] scroll-snap
 - [x] border-x border-y width & color
 - [x] rename overflow-clip to text-clip **BREAKING**
 - [x] rename overflow-ellipsis to text-ellipsis
 - [x] flex-basis
 - [x] fit-content for min/max-width/height
 - [x] min/max-content for min/max-height
 - [x] grow- shink- utilities
 - [x] text-decoration-color
 - [x] outline-style, outline-color, outline-width, outline-offset
 - [x] placeholder
 - [x] portrait and landscape variants
 - [x] text-decoration-style, -thickness, -offset
 - [x] ::before & ::after 
 - [ ] arbitrary values (e.g. `m-[calc(40%+10vh)]`)
 - [x] arbitrary properties (e.g. `hover:[mask-type:alpha]`)

### CODE REVIEW

**Comment by jamesnvc** [comment]
Another semantic compatibility question...currently, Girouette seems to be applying state variants in the opposite order as Tailwind does -- for example, `file:hover:X` in Girouette will be `.X::file-selector-button:hover`, whereas in Tailwind that would be `.X:hover::file-selector-button`. Arguably Girouette's ordering makes more sense (since it matches the order you write), but it is a subtle difference that might be worth calling out.

**Comment by jamesnvc** [comment]
Okay; I've added most of the new things in Tailwind 2.  The main exception is support for arbitrary values (e.g. `margin-[calc(1%+1vh)]`). I've omitted this for now (except for `content`, as it's kind of required for that) because 1. it is probably less important for Girouette, since we already have the ability to pass arbitrary lengths (although this is, strictly speaking, more powerful) and 2. it will touch basically every rule, making this giant diff even larger. If there's interest in that, I think it should be a separate PR.

As far as I can tell, the one breaking change is the `overflow-clip` and `overflow-ellipsis` classes changing to be `text-clip` and `text-ellipsis`, and `overflow-clip` now setting `overflow: clip` (instead of `text-overflow: clip`).

**Comment by green-coder** [comment]
🎉 Thanks for the amazing contribution @jamesnvc. I might start the review and integration this weekend.

**Comment by green-coder** [comment]
`outline-black` and `outline-white` has a breaking change from tailwind v2 to v3. I need to remember to add them to the changelog.

**Comment by green-coder** [comment]
Note: [MDN says](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding) that `scroll-padding` can also accept percentage. I am adding it.

**Comment by green-coder** [comment]
Note to self: the params for the shadows are different in v2 and v3.

**Pull request merged**
