### PR TITLE
Fix setting opacity of background color

### PR DESCRIPTION
**Pull request by jamesnvc**
If setting the --gi-bg-opacity with the same class as the one that is setting the background color, then a .bg-opacity-N won't override the variable. Instead, we can use the var-with-fallback for the background-color class.

### CODE REVIEW

**Comment by jamesnvc** [comment]
While tailwind does it the original way, I think it only works there because of the order the classes appear in the CSS file; with girouette dynamically generating the CSS, I guess sometimes it might work and other times it would not. This approach will hopefully be more robust and exhibit the desired behaviour.

**Comment by green-coder** [comment]
> If setting the --gi-bg-opacity with the same class as the one that is setting the background color, then a .bg-opacity-N won't override the variable.

To make sure that I understand correctly, can you please give a code sample which shows the problem?

**Comment by jamesnvc** [comment]
When I was testing, just adding any background colour then adding an opacity later caused the issue, but I was using a non-standard build process. I will try to make a minimal example and see if it’s reproducible.

**Comment by green-coder** [comment]
Thank you. The code sample will help for 3 reasons:
- it avoids small misunderstandings when communicating about the problem,
- it makes sure that the problem is solved afterward,
- it opens up the possibility of having a different way to solve it.

**Comment by jamesnvc** [comment]
Understood! Sorry I didn't leave one before -- I was in the process of building something else and then left on a little camping trip for a few days.

**Comment by jamesnvc** [comment]
Okay, it looks like it depends on the sorting order -- from the example reagent demo in the repo, simply adding the class "bg-opacity-50" to the div with the class "bg-red-200" doesn't work. Looking at the generated CSS, we can see that this happens because the `bg-red-200` class is output above the `bg-opacity-50` style, so overriding doesn't work.

It will happen to work if one adds the opacity to one of the other divs, since they get output before the opacity style, in which case the `bg-opacity-50` style gets precedence.

```diff
modified   example/reagent-demo/src/acme/frontend/app.cljc
@@ -7,7 +7,7 @@
 
    ;; Demonstrates the use of arbitrary values in flex layouts
    [:h1.flex.space-x-2
-    [:div.flex-1.p-4.text-center.rounded-lg.bg-red-200 "hello"]
+    [:div.flex-1.p-4.text-center.rounded-lg.bg-red-200.bg-opacity-50 "hello"]
     [:div.flex-2.p-4.text-center.rounded-lg.bg-green-200 "the"]
     [:div.p-4.text-center.rounded-lg.bg-blue-200 {:class "flex-9/3"} "world"]]
 
```

**Comment by green-coder** [comment]
Thanks to your precise description, I was able to reproduce the bug on my computer.

Your patch seems to solve the problem, but I would like to solve it differently, by introducing an ordering between the different rules in the generated file. The ordering feature might be useful to the users of the library in different situations, that's why I favor this solution.

**Comment by green-coder** [comment]
@jamesnvc I pushed a commit on `master`, please let me know if it totally solves the problem of this PR or not yet.

**Comment by jamesnvc** [comment]
Looks good to me!

**Pull request closed without merging**
